[package]
name = "ocassion"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
colored = "3"
dirs = "6.0.0"
map-macro = { version = "0.3.0", features = ["std"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
temp-env = "0.3.6"
thiserror = "2.0.12"
