name: Build to Github Releases and crates.io
on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  github-releases:
    name: Github Releases - ${{ matrix.platform.release-for }}
    strategy:
      matrix:
        platform:
          - release-for: linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - release-for: linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - release-for: windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - release-for: windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc

          - release-for: macos-x86_64
            runs-on: macos-latest
            target: x86_64-apple-darwin

          - release-for: macos-aarch64
            runs-on: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build executable
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: occasion 
          archive-name: occasion-${{ matrix.platform.release-for }}
          target: ${{ matrix.platform.target }}
          changes-file: ""

  crates_io:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO }}

