name: Create release on milestone closure

on:
  milestone:
    types:
      - closed

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Extract Milestone Title
        id: extract
        run: |
          echo "MILESTONE_TITLE=${{ github.event.milestone.title }}" >> $GITHUB_ENV

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.MILESTONE_CI_GITHUB_TOKEN }}
        run: |
          gh release create "${MILESTONE_TITLE}" \
            --title "${MILESTONE_TITLE}" \
            --generate-notes
